events {}

http {
    include mime.types;
    sendfile on;

    client_max_body_size 20M; 

    server {
        listen 80;
        root /usr/share/nginx/html;

        location / {
            try_files $uri /index.html;
        }

        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
            root /usr/share/nginx/html;
            expires 30d;
            add_header Cache-Control "public, no-transform";
        }
    }
}